apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-httpbin
  labels:
    app: httpbin
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: httpbin
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: httpbin
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: httpbin
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
